---
title: "TODO"
author: "Felipe Campelo, Claus Aranha"
date: "30/01/2016"
output: html_document
---


## For the package itself
### Features needed for paper experiments
- OUTPUT: Opcoes de output para logfile

### Code Issues
- variation_diffmut: Line 90 - bigZ is created if not in environment, but is not returned to environment. Correct?
- Asserts that test the validity and existence of parameters need to give better return messages
- Through the code, we have three ways to access environment values: using call.env, passing the env as parameter, passing the values directly as parameters. We need to formalize a decision of which ways to use, and when, so it is consistent across modules in the package.
- STRUCTURE: discuss spaghettification of code in update_population
- bigZ, generated by scalarize_values, has dims (T+1,Subprobs). 
  This is inconsistent with other matrices (B,X,Y) where the number of rows is equal to the number of subproblems
- update_best lines 67/68

### Documentation Issues
- Vigneta about how to define a problem function and a violation function (eg: both functions require '...' in parameter list )
- Vigneta sobre o variation stack (Incluindo o fato de que repair operators vao no variation stack)


## For the paper:
- Having the complete package: Define a search space of algorithms, 
  and use the irace to find a well adjusted MOEAD variation
- Comment about the utility of the package for the reproducibility

- Finish thinking the experiments.
- Perform and document experiments.
- Finish documenting the modules.

## Wishlist (can be done after paper is out)
- VARIATION: more variation operators
- DEFINE NEIGHBORHOOD: Make it un-hardcoded
- GENERATE POPULATION: Make it un-hardcoded
- SCALARIZATION: Verify that iPBI is correct (check with Hiroyuki Sato -- Institute of ElectroCommunication in Tokyo)
- UPDATE POP: implement other alternatives for objective scaling
- OUTPUT: Logging hooks for user-defined variation operators
- PROFILE: Profile the package under different argument combinations and identify bottlenecks
