<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Fine tuning MOEA/D configurations using MOEADr and irace • MOEADr</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Fine tuning MOEA/D configurations using MOEADr and irace">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">MOEADr</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">1.1.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/Basic_Usage.html">Basic Usage of the MOEADr Package</a>
    </li>
    <li>
      <a href="../articles/Comparison_Usage.html">Fine tuning MOEA/D configurations using MOEADr and irace</a>
    </li>
    <li>
      <a href="../articles/Modification_Usage.html">Testing New Operators using the MOEADr Package</a>
    </li>
    <li>
      <a href="../articles/problem-definition.html">Defining Problems in the MOEADr Package</a>
    </li>
    <li>
      <a href="../articles/writing-functions-for-moeadr.html">Writing Extensions for the MOEADr Package</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Fine tuning MOEA/D configurations using MOEADr and irace</h1>
                        <h4 class="author">Claus Aranha, Felipe Campelo</h4>
            
            <h4 class="date">2018-07-01</h4>
      
      
      <div class="hidden name"><code>Comparison_Usage.Rmd</code></div>

    </div>

    
    
<p>For this example, we adapt the tuning protocol proposed by Bezerra <em>et al.</em> (2016)<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>, employing the <em>Iterated Racing</em> procedure by Lopez-Ibanez <em>et al.</em> (2016)<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a>. Using the <strong>irace</strong> package, we automatically assemble and fine-tune a MOEA/D configuration based on the components available in the <strong>MOEADr</strong> package.</p>
<div id="fine-tuning-setup" class="section level2">
<h2 class="hasAnchor">
<a href="#fine-tuning-setup" class="anchor"></a>Fine tuning setup</h2>
<p>Ten unconstrained test problems from the CEC2009 competition<a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a> are used, with dimensions ranging from 20 to 60. Dimensions 30, 40 and 50 were reserved for testing, while all others were used for the training effort. To quantify the quality of the set of solutions returned by a candidate configuration we use the Inverted Generational Distance (IGD). The number of subproblems was fixed as <span class="math inline">\(100\)</span> for <span class="math inline">\(m=2\)</span> and <span class="math inline">\(150\)</span> for <span class="math inline">\(m=3\)</span><a href="#fn4" class="footnoteRef" id="fnref4"><sup>4</sup></a>.</p>
<p>We define a tuning budget of 20,000 runs. The possible configurations are composed from the following choices:</p>
<ul>
<li>Decomposition Strategy: SLD or Uniform;</li>
<li>Scalar Aggregation function: WT, PBI or AWB;</li>
<li>Type of neighborhood: by weights or by incumbent solutions;</li>
<li>Type of Update: Standard, Restricted, or Best Subproblem;</li>
<li>Variation Stack: See below;</li>
</ul>
<p>For every combination, the parameters of each component (e.g. <span class="math inline">\(\theta^{pbi}\)</span> for the PBI aggregation function) were also included as part of the tuning experiment. Objective scaling was employed in all cases. No constraint handling was required, and the stop criterion was set as 100,000 evaluations.</p>
<p>The variation stack was composed of three to five operators, using the following rules: the first and second operators could be any of the “traditional” operators currently available in the <strong>MOEADr</strong> package: SBX, Polynomial Mutation, Differential Mutation, and Binomial Recombination. The third operator could be any of these, or “none” (i.e., not present). The fourth operator could be either a local search operator or “none”. Finally, the variation stack always finished with the truncation repair operator (mainly to avoid errors with the implementation of the test functions). No restrictions were placed on repeats of the variation operators, and the specific conditional parameters for each operator were allowed to be tuned independently for each position in the variation stack.</p>
</div>
<div id="irace-configuration" class="section level2">
<h2 class="hasAnchor">
<a href="#irace-configuration" class="anchor"></a><strong>irace</strong> configuration</h2>
<p>Here we describe the necessary setup to run the experiment above. First, loading the necessary packages and basic configuration of <em>irace</em>. (<em>parameters.txt</em>, <em>forbidden.txt</em> and other files are only included in the source version of the <em>MOEADr</em> package)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">suppressPackageStartupMessages</span>(<span class="kw">library</span>(irace))
<span class="kw">suppressPackageStartupMessages</span>(<span class="kw">library</span>(parallel))
<span class="kw">suppressPackageStartupMessages</span>(<span class="kw">library</span>(smoof))
<span class="kw">suppressPackageStartupMessages</span>(<span class="kw">library</span>(MOEADr))

scenario                &lt;-<span class="st"> </span>irace<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/irace/topics/defaultScenario">defaultScenario</a></span>()
scenario<span class="op">$</span>seed           &lt;-<span class="st"> </span><span class="dv">123456</span> <span class="co"># Seed for the experiment</span>
scenario<span class="op">$</span>targetRunner   &lt;-<span class="st"> "target.runner"</span> <span class="co"># Runner function (def. below)</span>
scenario<span class="op">$</span>forbiddenFile  &lt;-<span class="st"> "../inst/extdata/forbidden.txt"</span> <span class="co"># forbidden configs</span>
scenario<span class="op">$</span>debugLevel     &lt;-<span class="st"> </span><span class="dv">1</span>
scenario<span class="op">$</span>maxExperiments &lt;-<span class="st"> </span><span class="dv">20000</span> <span class="co"># Tuning budget</span>
scenario<span class="op">$</span>testNbElites   &lt;-<span class="st"> </span><span class="dv">7</span>     <span class="co"># test all final elite configurations</span>

<span class="co"># Number of cores to be used by irace (set with caution!)</span>
nc                      &lt;-<span class="st"> </span>parallel<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/parallel/topics/detectCores">detectCores</a></span>() <span class="op">-</span><span class="st"> </span><span class="dv">1</span>
scenario<span class="op">$</span>parallel       &lt;-<span class="st"> </span>nc

<span class="co"># Read tunable parameter list from file</span>
parameters &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/irace/topics/readParameters">readParameters</a></span>(<span class="st">"../inst/extdata/parameters.txt"</span>)</code></pre></div>
<p>Second, it is necessary to generate the training instances based on the benchmark function implementations in package <strong>smoof</strong>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#===============</span>
### Build training instances
fname   &lt;-<span class="st"> </span><span class="kw">paste0</span>(<span class="st">"UF_"</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">10</span>)
dims    &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">20</span><span class="op">:</span><span class="dv">29</span>,
             <span class="dv">31</span><span class="op">:</span><span class="dv">39</span>,
             <span class="dv">41</span><span class="op">:</span><span class="dv">49</span>,
             <span class="dv">51</span><span class="op">:</span><span class="dv">60</span>)

allfuns            &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(fname, dims, <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)
scenario<span class="op">$</span>instances &lt;-<span class="st"> </span><span class="kw">paste0</span>(allfuns[,<span class="dv">1</span>], <span class="st">"_"</span>, allfuns[,<span class="dv">2</span>])

<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(allfuns)){
  <span class="kw">assign</span>(<span class="dt">x     =</span> scenario<span class="op">$</span>instances[i],
         <span class="dt">value =</span> <span class="kw"><a href="../reference/make_vectorized_smoof.html">make_vectorized_smoof</a></span>(<span class="dt">prob.name  =</span> <span class="st">"UF"</span>,
                                       <span class="dt">dimensions =</span> allfuns[i, <span class="dv">2</span>],
                                       <span class="dt">id         =</span> <span class="kw">as.numeric</span>(<span class="kw">strsplit</span>(allfuns[i, <span class="dv">1</span>], <span class="st">"_"</span>)
                                                               [[<span class="dv">1</span>]][<span class="dv">2</span>]))) }

### Build test instances
dims                   &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">50</span>)
allfuns                &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(fname, dims, <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)
scenario<span class="op">$</span>testInstances &lt;-<span class="st"> </span><span class="kw">paste0</span>(allfuns[,<span class="dv">1</span>], <span class="st">"_"</span>, allfuns[,<span class="dv">2</span>])

<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(allfuns)){
  <span class="kw">assign</span>(<span class="dt">x     =</span> scenario<span class="op">$</span>testInstances[i],
         <span class="dt">value =</span> <span class="kw"><a href="../reference/make_vectorized_smoof.html">make_vectorized_smoof</a></span>(<span class="dt">prob.name  =</span> <span class="st">"UF"</span>,
                                       <span class="dt">dimensions =</span> allfuns[i, <span class="dv">2</span>],
                                       <span class="dt">id         =</span> <span class="kw">as.numeric</span>(<span class="kw">strsplit</span>(allfuns[i, <span class="dv">1</span>], <span class="st">"_"</span>)
                                                               [[<span class="dv">1</span>]][<span class="dv">2</span>]))) }</code></pre></div>
<p>Third, we need to specify the code that will generate a MOEA/D configuration based on the parameter string created by the <em>irace</em> routine:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">target.runner &lt;-<span class="st"> </span><span class="cf">function</span>(experiment, scenario){
  <span class="kw">force</span>(experiment)
  conf &lt;-<span class="st"> </span>experiment<span class="op">$</span>configuration
  inst &lt;-<span class="st"> </span>experiment<span class="op">$</span>instance

  <span class="co"># Assemble moead input lists</span>
  ## 1. Problem
  fdef    &lt;-<span class="st"> </span><span class="kw">unlist</span>(<span class="kw">strsplit</span>(inst, <span class="dt">split =</span> <span class="st">"_"</span>))
  uffun   &lt;-<span class="st"> </span>smoof<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/smoof/topics/makeUFFunction">makeUFFunction</a></span>(<span class="dt">dimensions =</span> <span class="kw">as.numeric</span>(fdef[<span class="dv">3</span>]),
                                   <span class="dt">id         =</span> <span class="kw">as.numeric</span>(fdef[<span class="dv">2</span>]))
  fattr   &lt;-<span class="st"> </span><span class="kw">attr</span>(uffun, <span class="st">"par.set"</span>)
  problem &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">name       =</span> inst,
                  <span class="dt">xmin       =</span> fattr<span class="op">$</span>pars<span class="op">$</span>x<span class="op">$</span>lower,
                  <span class="dt">xmax       =</span> fattr<span class="op">$</span>pars<span class="op">$</span>x<span class="op">$</span>upper,
                  <span class="dt">m          =</span> <span class="kw">attr</span>(uffun, <span class="st">"n.objectives"</span>))

  ## 2. Decomp
  decomp &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">name =</span> conf<span class="op">$</span>decomp.name)
  <span class="cf">if</span> (problem<span class="op">$</span>m <span class="op">==</span><span class="st"> </span><span class="dv">2</span>){ <span class="co"># &lt;-- 2 objectives</span>
    <span class="cf">if</span>(decomp<span class="op">$</span>name <span class="op">==</span><span class="st"> "SLD"</span>) decomp<span class="op">$</span>H &lt;-<span class="st"> </span><span class="dv">99</span> <span class="co"># &lt;-- yields N = 100</span>
    <span class="cf">if</span>(decomp<span class="op">$</span>name <span class="op">==</span><span class="st"> "Uniform"</span>) decomp<span class="op">$</span>N &lt;-<span class="st"> </span><span class="dv">100</span>
  } <span class="cf">else</span> { <span class="co"># &lt;-- 3 objectives</span>
    <span class="cf">if</span>(decomp<span class="op">$</span>name <span class="op">==</span><span class="st"> "SLD"</span>) decomp<span class="op">$</span>H &lt;-<span class="st"> </span><span class="dv">16</span> <span class="co"># &lt;-- yields N = 153</span>
    <span class="cf">if</span>(decomp<span class="op">$</span>name <span class="op">==</span><span class="st"> "Uniform"</span>) decomp<span class="op">$</span>N &lt;-<span class="st"> </span><span class="dv">150</span>
  }

  ## 3. Neighbors
  neighbors &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">name    =</span> conf<span class="op">$</span>neighbor.name,
                    <span class="dt">T       =</span> conf<span class="op">$</span>T,
                    <span class="dt">delta.p =</span> conf<span class="op">$</span>delta.p)

  ## 4. Aggfun
  aggfun &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">name =</span> conf<span class="op">$</span>aggfun.name)
  <span class="cf">if</span> (aggfun<span class="op">$</span>name <span class="op">==</span><span class="st"> "PBI"</span>) aggfun<span class="op">$</span>theta &lt;-<span class="st"> </span>conf<span class="op">$</span>aggfun.theta

  ## 5. Update
  update &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">name       =</span> conf<span class="op">$</span>update.name,
                 <span class="dt">UseArchive =</span> conf<span class="op">$</span>UseArchive)
  <span class="cf">if</span> (update<span class="op">$</span>name <span class="op">!=</span><span class="st"> "standard"</span>) update<span class="op">$</span>nr &lt;-<span class="st"> </span>conf<span class="op">$</span>nr
  <span class="cf">if</span> (update<span class="op">$</span>name <span class="op">==</span><span class="st"> "best"</span>)     update<span class="op">$</span>Tr &lt;-<span class="st"> </span>conf<span class="op">$</span>Tr

  ## 6. Scaling
  scaling &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">name =</span> <span class="st">"simple"</span>)

  ## 7. Constraint
  constraint&lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">name =</span> <span class="st">"none"</span>)

  ## 8. Stop criterion
  stopcrit  &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="kw">list</span>(<span class="dt">name    =</span> <span class="st">"maxeval"</span>,
                         <span class="dt">maxeval =</span> <span class="dv">100000</span>))

  ## 9. Echoing
  showpars  &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">show.iters =</span> <span class="st">"none"</span>)

  ## 10. Variation stack
  variation &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="kw">list</span>(<span class="dt">name =</span> conf<span class="op">$</span>varop1),
                    <span class="kw">list</span>(<span class="dt">name =</span> conf<span class="op">$</span>varop2),
                    <span class="kw">list</span>(<span class="dt">name =</span> conf<span class="op">$</span>varop3),
                    <span class="kw">list</span>(<span class="dt">name =</span> conf<span class="op">$</span>varop4),
                    <span class="kw">list</span>(<span class="dt">name =</span> <span class="st">"truncate"</span>))

  <span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq_along</span>(variation)){
    <span class="cf">if</span> (variation[[i]]<span class="op">$</span>name <span class="op">==</span><span class="st"> "binrec"</span>) {
      variation[[i]]<span class="op">$</span>rho &lt;-<span class="st"> </span><span class="kw">get</span>(<span class="kw">paste0</span>(<span class="st">"binrec.rho"</span>, i), conf)
    }
    <span class="cf">if</span> (variation[[i]]<span class="op">$</span>name <span class="op">==</span><span class="st"> "diffmut"</span>) {
      variation[[i]]<span class="op">$</span>basis &lt;-<span class="st"> </span><span class="kw">get</span>(<span class="kw">paste0</span>(<span class="st">"diffmut.basis"</span>, i), conf)
      variation[[i]]<span class="op">$</span>Phi   &lt;-<span class="st"> </span><span class="ot">NULL</span>
    }
    <span class="cf">if</span> (variation[[i]]<span class="op">$</span>name <span class="op">==</span><span class="st"> "polymut"</span>) {
      variation[[i]]<span class="op">$</span>etam &lt;-<span class="st"> </span><span class="kw">get</span>(<span class="kw">paste0</span>(<span class="st">"polymut.eta"</span>, i), conf)
      variation[[i]]<span class="op">$</span>pm   &lt;-<span class="st"> </span><span class="kw">get</span>(<span class="kw">paste0</span>(<span class="st">"polymut.pm"</span>, i), conf)
    }
    <span class="cf">if</span> (variation[[i]]<span class="op">$</span>name <span class="op">==</span><span class="st"> "sbx"</span>) {
      variation[[i]]<span class="op">$</span>etax &lt;-<span class="st"> </span><span class="kw">get</span>(<span class="kw">paste0</span>(<span class="st">"sbx.eta"</span>, i), conf)
      variation[[i]]<span class="op">$</span>pc   &lt;-<span class="st"> </span><span class="kw">get</span>(<span class="kw">paste0</span>(<span class="st">"sbx.pc"</span>, i), conf)
    }
    <span class="cf">if</span> (variation[[i]]<span class="op">$</span>name <span class="op">==</span><span class="st"> "localsearch"</span>) {
      variation[[i]]<span class="op">$</span>type     &lt;-<span class="st"> </span>conf<span class="op">$</span>ls.type
      variation[[i]]<span class="op">$</span>gamma.ls &lt;-<span class="st"> </span>conf<span class="op">$</span>gamma.ls
    }
  }

  ## 11. Seed
  seed &lt;-<span class="st"> </span>conf<span class="op">$</span>seed
  
  <span class="co"># Run MOEA/D</span>
  out &lt;-<span class="st"> </span><span class="kw"><a href="../reference/moead.html">moead</a></span>(<span class="dt">preset =</span> <span class="ot">NULL</span>,
               problem, decomp,  aggfun, neighbors, variation, update,
               constraint, scaling, stopcrit, showpars, seed)

  <span class="co"># return IGD based on reference data</span>
  Yref &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(<span class="kw">read.table</span>(<span class="kw">paste0</span>(<span class="st">"../inst/extdata/pf_data/"</span>,
                                      fdef[<span class="dv">1</span>], fdef[<span class="dv">2</span>], <span class="st">".dat"</span>)))
  <span class="kw">return</span>(<span class="kw">list</span>(<span class="dt">cost =</span> <span class="kw"><a href="../reference/calcIGD.html">calcIGD</a></span>(<span class="dt">Y =</span> out<span class="op">$</span>Y, <span class="dt">Yref =</span> Yref)))
}</code></pre></div>
<p>Finally, we run the experiment, and save the outputs. Note that this experiment will take a long time to run (24 hours in a 24 cluster machine), so take that into account when reproducing these results. For more details on the code above, check the documentation of the <strong>irace</strong> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Running the experiment
irace.output &lt;-<span class="st"> </span>irace<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/irace/topics/irace">irace</a></span>(scenario, parameters)
<span class="kw">saveRDS</span>(irace.output, <span class="st">"../inst/extdata/RESULTS.rds"</span>)
<span class="kw">file.copy</span>(<span class="dt">from =</span> <span class="st">"irace.Rdata"</span>, <span class="dt">to =</span> <span class="st">"../inst/extdata/irace-tuning.Rdata"</span>)


## Test returned configurations on test instances
<span class="kw"><a href="http://www.rdocumentation.org/packages/irace/topics/testing.main">testing.main</a></span>(<span class="dt">logFile =</span> <span class="st">"../inst/extdata/irace-tuning.Rdata"</span>)
<span class="kw">file.copy</span>(<span class="dt">from =</span> <span class="st">"irace.Rdata"</span>, <span class="dt">to =</span> <span class="st">"../inst/extdata/irace-testing.Rdata"</span>)</code></pre></div>
</div>
<div id="results" class="section level2">
<h2 class="hasAnchor">
<a href="#results" class="anchor"></a>Results</h2>
<p>First let’s plot the IGD value achieved by the final configurations over the test problems:</p>
<pre><code>## Loading required package: reshape2</code></pre>
<pre><code>## Using Problem, Dimension, Objectives as id variables</code></pre>
<pre><code>## Loading required package: ggplot2</code></pre>
<p><img src="Comparison_Usage_files/figure-html/reshape2,%20ggplot2-1.png" width="672"></p>
<p>The final MOEA/D configuration obtained by this experiment is described in the table below. The best configuration is presented in the first two columns. The third column, together with the figure following, provides the consensus value of each component, measured as the rate of occurrence of each component in the seven final configurations returned by the Iterated Racing procedure. These results suggest that the automated assembling and tuning method reached a reasonably solit consensus, in terms of the components used as well as the values returned for the numeric parameters.</p>
<table style="width:53%;" class="table">
<colgroup>
<col width="19%">
<col width="13%">
<col width="19%">
</colgroup>
<thead><tr class="header">
<th><strong>Component</strong></th>
<th><strong>Value</strong></th>
<th><strong>Consensus</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Decomposition</td>
<td>SLD</td>
<td>1.00</td>
</tr>
<tr class="even">
<td>Aggregation Function</td>
<td>AWT</td>
<td>1.00</td>
</tr>
<tr class="odd">
<td>Objective Scaling</td>
<td>simple</td>
<td>Fixed</td>
</tr>
<tr class="even">
<td>Neighborhood</td>
<td>by <span class="math inline">\(x\)</span><br><span class="math inline">\(T = 11\)</span><br><span class="math inline">\(\delta_p = 0.909\)</span>
</td>
<td>1.00<br>see Figure<br>see Figure</td>
</tr>
<tr class="odd">
<td>Variation Stack (1)</td>
<td>Differential Mutation<br><span class="math inline">\(basis = "rand"\)</span><br><span class="math inline">\(\phi \sim U(0,1)\)</span>
</td>
<td>1.00<br>1.00<br>Fixed</td>
</tr>
<tr class="even">
<td>Variation Stack (2)</td>
<td>Binomial Recombination<br><span class="math inline">\(\rho_1 = 0.495\)</span>
</td>
<td>
<br>1.00<br>see Figure</td>
</tr>
<tr class="odd">
<td>Variation Stack (3)</td>
<td>Binomial Recombination<br><span class="math inline">\(\rho_2 = 0.899\)</span>
</td>
<td>
<br>1.00<br>see Figure</td>
</tr>
<tr class="even">
<td>Variation Stack (4)</td>
<td>Truncate</td>
<td>Fixed</td>
</tr>
<tr class="odd">
<td>Update</td>
<td>Restricted<br><span class="math inline">\(nr=1\)</span>
</td>
<td>1.00<br>1.00</td>
</tr>
</tbody>
</table>
<pre><code>## Plotting: T</code></pre>
<pre><code>## Plotting: delta.p</code></pre>
<pre><code>## Plotting: binrec.rho2</code></pre>
<pre><code>## Plotting: binrec.rho3</code></pre>
<p><img src="Comparison_Usage_files/figure-html/ggplot2-1.png" width="672"></p>
<p>A feature that may seem surprising at first glance is the two sequential applications of Binomial Recombination in the Variation Stack. This means that the results of a Differential Mutation operator are recombined with the incumbent solutions at the (reasonably low) recombination rate <span class="math inline">\(\rho_1 = 0.495\)</span>; and then the resulting vectors are again recombined with the incumbent solutions, at a (much higher) rate <span class="math inline">\(\rho_2 = 0.899\)</span>. However, a quick review of the definition of Binomial Recombination and some elementary probability shows that these two sequential applications of binomial recombinations can be expressed as a single application with <span class="math inline">\(\rho = \rho_1\rho_2 = 0.445\)</span>. The fact that Iterated Racing converged to two operators instead of a single one can be explained by the fact that these situations are equivalent, coupled with the absence of any pressure towards more parsimonious expressions of the Variation Stack in the setup.</p>
<p>Another seemingly counterintuitive aspect of the final configurations reached is the absence of local search. A possible explanation lies in the interaction between the variation operators chosen (differential mutation + binomial recombination) with the type of neighborhood (by <span class="math inline">\(x\)</span>, with a very strong bias towards using points from the neighborhood for the variant operators - <span class="math inline">\(\delta_p = 0.909\)</span>). The use of points that are relatively similar in the space of decision variables may result in local exploration in this case, since the magnitude of the differential vectors tends to become relatively small. As the iterations progress, this Variation Stack would tend to perform local search movements, with larger pertubations potentially occurring whenever points are sampled from outside the neighborhoods (i.e., about 10% of the cases). It is therefore possible that this local exploration characteristic may have resulted in a MOEA/D configuration that does not benefit from an explicit local search operator.</p>
<p>Besides these considerations, the configurations returned by the Iterated Racing procedure present a few other interesting points. First, the use of a smaller neighborhood than is usually practiced in the literature (T = 11), with the neighborhood relations being defined at each iteration by the similarities between the incumbent solutions of each subproblem. Second, the use of a very strict Restricted Neighborhood Update, with <span class="math inline">\(n_r = 1\)</span>, which suggests an advantage in trying to maintain diversity instead of accelerating convergence. The use of the variation operators of the MOEAD/D-De <em>without</em> Polynomial Mutation (as is usually practiced in the MOEA/D-DE) is also curious, as it may indicate a more parsimonious variation stack than is usually practiced in the literature.</p>
</div>
<div id="recommendations" class="section level2">
<h2 class="hasAnchor">
<a href="#recommendations" class="anchor"></a>Recommendations</h2>
<p>As can be seen, exploring the space of possible component configurations and parameter values can render improved algorithmic configurations and new insights into the roles of specific components and parameter values.</p>
<p>Thus, we highly recommend that a similar approach is used when developing new components, in order to observe not only the individual performance of the novel component, but also its interaction with components which already exist in the MOEA/D environment.</p>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1"><p>Lecture Notes in Computer Science 9018:48–63, 2016.<a href="#fnref1">↩</a></p></li>
<li id="fn2"><p>Operations Research Perspectives 3:43-58, 2016<a href="#fnref2">↩</a></p></li>
<li id="fn3"><p>Functions UF1 to UF10 (<a href="http://dces.essex.ac.uk/staff/qzhang/moeacompetition09.htm" class="uri">http://dces.essex.ac.uk/staff/qzhang/moeacompetition09.htm</a>), using the standard implementation available in the <strong>smoof</strong> package.<a href="#fnref3">↩</a></p></li>
<li id="fn4"><p>For the Simplex Lattice Design the actual number was 153 for <span class="math inline">\(m = 3\)</span>, given the specifics of this method. Please refer to the documentation of function <em>decomposition_sld()</em> for details<a href="#fnref4">↩</a></p></li>
</ol>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#fine-tuning-setup">Fine tuning setup</a></li>
      <li><a href="#irace-configuration"><strong>irace</strong> configuration</a></li>
      <li><a href="#results">Results</a></li>
      <li><a href="#recommendations">Recommendations</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Felipe Campelo, Claus Aranha.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
