#' Three-point quadratic approximation local search
#'
#' Three-point quadratic approximation (TPQA) local search implementation for
#' the MOEA/D
#'
#' This routine implements the 3-point quadratic approximation local search for
#' the MOEADr package. Check the references for details.
#'
#' @param X Population matrix
#' @param Y Matrix of objective function values for X
#' @param B Matrix of neighborhoods (generated by [define_neighborhood()])
#' @param W matrix of weights (generated by [generate_weights()]).
#' @param which.x logical vector indicating which subproblems should undergo
#' local search
#' @param eps threshold for using the quadratic approximation value
#' @param ... other parameters (unused, included for compatibility with
#' generic call)
#'
#' @section References:
#' Y. Tan, Y. Jiao, H. Li, X. Wang,
#' "A modification to MOEA/D-DE for multiobjective optimization problems with
#' complicated Pareto sets",
#' Information Sciences 213(1):14-38, 2012.
#'
#' @return Matrix \code{X}' containing the modified population
#'
#' @export

ls_tpqa <- function(X, Y, B, W, which.x, eps = 1e-6, ...){

  # ========== Error catching and default value definitions
  # Most error catching and default value definitions are assumed to have been
  # verified in the calling functions, and will not be repeated here.
  assertthat::assert_that(is.numeric(eps), eps >= 0,
                          nrow(X) == nrow(Y),
                          nrow(Y)  == dim(B))
  if(is.null(tau.ls)) tau.ls     <- Inf
  if(is.null(gamma.ls)) gamma.ls <- 0
  if(is.null(unsync)) unsync     <- TRUE
  if(is.null(trunc.x)) trunc.x   <- TRUE

  assertthat::assert_that(assertthat::has_name(call.env, "iter"),
                          type %in% valid.types,
                          assertthat::is.count(tau.ls),
                          is_within(gamma.ls, 0, 1),
                          is.logical(unsync),
                          is.logical(trunc.x))


  # Return results
  return(X)
}
