#' summary.moeadoutput
#'
#' S3 method for summarizing _moeadoutput_ objects (the output of [moead()]).
#'
#' @param object list object of class _moeadoutput_
#'                     (generated by [moead()])
#' @param useArchive logical flag to use information from `object$Archive`.
#'                   Only used if object$Archive is not `NULL`.
#' @param viol.threshold threshold of tolerated constraint violation, used to
#'                       determine feasibility of points in `object`.
#' @param ndigits number of decimal places to use for the ideal and nadir estimates
#' @param ... other parameters to be passed down to specific summary functions (currently unused)
#'
#' @export
#'
summary.moeadoutput <- function(object,
                                ...,
                                useArchive        = FALSE,
                                viol.threshold    = 1e-6,
                                ndigits           = 3)
  {

  # Error checking
  assertthat::assert_that(
    "moeadoutput" %in% class(object),
    is.logical(useArchive),
    is.numeric(viol.threshold) && viol.threshold >= 0,
    assertthat::is.count(ndigits))

  # ===========================================================================
  # Calculate information for summary

  if(useArchive && !is.null(object$Archive)){
    Y <- object$Archive$Y
    V <- object$Archive$V
  } else {
    Y <- object$Y
    V <- object$V
  }

  feas.idx <- rep(TRUE, nrow(Y))
  if(!is.null(V)) feas.idx <- (rowSums(V$Vmatrix > viol.threshold) == 0)

  npts  <- nrow(Y)
  nfeas <- sum(feas.idx)
  nndom <- sum(find_nondominated_points(Y[feas.idx, ]))

  ideal.est <- apply(Y[feas.idx, ], 2, min)
  nadir.est <- apply(Y[feas.idx, ], 2, max)


  # ===========================================================================
  # Plot summary list

  cat("\nSummary of MOEA/D run")
  cat("\n#====================================")
  cat("\nTotal function evaluations: ", object$nfe)
  cat("\nTotal iterations: ", object$n.iter)
  cat("\nPopulation size: ", npts)
  cat("\nFeasible points found: ", nfeas,
      paste0("(", signif(100 * nfeas / npts, 3), "%"),
      "of total)")
  cat("\nNondominated points found: ", nndom,
      paste0("(", signif(100 * nndom / npts, 3), "%"),
      "of total)")
  cat("\nEstimated ideal point: ", round(ideal.est, ndigits))
  cat("\nEstimated nadir point: ", round(nadir.est, ndigits))
  cat("\n#====================================")

}
