#' summary.moeadoutput
#'
#' S3 method for summarizing _moeadoutput_ objects (the output of [moead()]).
#'
#' @param moead.output list object of class _moeadoutput_
#'                     (generated by [moead()])
#' @param useArchive logical flag to use information from `moead.output$Archive`.
#'                   Only used if moead.output$Archive is not `NULL`.
#' @param viol.threshold threshold of tolerated constraint violation, used to
#'                       determine feasibility of points in `moead.output`.
#' @param ndigits number of decimal places to use for the ideal and nadir estimates
#'
#' @export
#'
summary.moeadoutput <- function(moead.output,
                                useArchive        = FALSE,
                                viol.threshold    = 1e-6,
                                ndigits           = 3,
                                ...) {

  # Error checking
  assertthat::assert_that(
    "moeadoutput" %in% class(moead.output),
    is.logical(useArchive),
    is.logical(feasible.only),
    is.logical(nondominated.only),
    is.numeric(viol.threshold) && viol.threshold >= 0)

  # ===========================================================================
  # Calculate information for summary

  if(useArchive && !is.null(moead.output$Archive)){
    Y <- moead.output$Archive$Y
    V <- moead.output$Archive$V
  } else {
    Y <- moead.output$Y
    V <- moead.output$V
  }

  feas.idx <- rep(TRUE, nrow(Y))
  if(!is.null(V)) feas.idx <- (rowSums(V$Vmatrix > viol.threshold) == 0)

  npts  <- nrow(Y)
  nfeas <- sum(feas.idx)
  nndom <- sum(find_nondominated_points(Y[feas.idx, ]))

  ideal.est <- apply(Y[feas.idx, ], 2, min)
  nadir.est <- apply(Y[feas.idx, ], 2, max)


  # ===========================================================================
  # Preprocess data for summarization

  cat("\nSummary of MOEA/D run")
  cat("\n#====================================")
  cat("\nTotal function evaluations: ", moead.output$nfe)
  cat("\nTotal iterations: ", moead.output$niter)
  cat("\nPopulation size: ", npts)
  cat("\nFeasible points found: ", nfeas,
      paste0("(", signif(100 * nfeas / npts, 3), "%"),
      "of total)")
  cat("\nNondominated points found: ", nndom,
      paste0("(", signif(100 * nndom / npts, 3), "%"),
      "of total)")
  cat("\nEstimated ideal point: ", round(ideal.est, ndigits))
  cat("\nEstimated nadir point: ", round(nadir.est, ndigits))
  cat("\n#====================================")

}
