#' Differential Mutation
#'
#' Differential Mutation implementation for the MOEA/D
#'
#' This function generalizes many variations of the Differential Mutation
#' operator with general form:
#'
#' u <- x_basis + Phi(x_a - x_b)
#'
#' Where u is the new candidate vector, Phi is a real number != 0,
#' and x_basis, x_a and x_b are distinct vectors in the population.
#'
#' This function include the following variations of this operator:
#'
#' \itemize{
#'    \item Phi may be a constant, user provided parameter, or randomly choosen.
#'    \item X_basis can be a random vector from the population
#'    \item X_basis can be the mean point in the T neighborhood
#'    \item X_basis can be the weighted mean point in the T neighborhood
#' }
#'
#' @param X Population matrix
#' @param P Matrix of selection probabilities (generated by
#' \code{define_neighborhood(...)})
#' @param phi Mutation parameter, random if NULL
#' @param basis how to select the basis vector, can be one of "random", "mean" or "weighted"
#' @param ... other parameters (unused, included for compatibility with
#' generic call)
#'
#' @return Matrix \code{X}' containing the mutated population
#'
#' @export

variation_differential <- function(X, P, phi = NULL, basis = 'random', ...){

  # ========== Error catching and default value definitions
  assertthat::assert_that(
    is.numeric(X) && is.matrix(X),
    is.numeric(P) && is.matrix(P) && is_within(P, 0, 1, strict = FALSE),
    identical(nrow(X), nrow(P)),
    nrow(P) == ncol(P),
    is.null(phi) || (is.numeric(phi) && phi != 0),
    is.element(basis,c('random', 'mean', 'weighted')))
  # ==========

  # Generate replacement indexes for xbasis, x0, x1
  # (Basis is recreated if 'mean' or 'random')
  R <- t(sapply(1:nrow(X), FUN = function(i) { sample.int(nrow(X), size = 3, replace = FALSE, prob = P[,i]) }))

  # TODO: Variations on the basis vector (R[1,]), as in the manuscript

  if (is.null(phi)) {
    phi <- runif(1)
  }

  Xn <- X[R[, 1], ] + phi*(X[R[, 2], ] - X[R[, 3], ])

  return(Xn)
}
