#' Local search Operators
#'
#' Local search operators for the MOEA/D
#'
#' This routine calls the local search operator for the MOEADr package, as part
#' of the call to [perform_variation()].
#'
#' Whenever local search is triggered for a given subproblem, it cancels
#' all other variation operators _for that subproblem_ and is executed directly
#' on the incumbent solution.
#'
#' This routine is intended to be used internally by [perform_variation()],
#' and should not be called directly by the user.
#'
#' @param ... arguments to be passed down to the specific `ls_xyz()` functions.
#' A list of available local search methods can be generated by
#' [get_localsearch_methods()]. Consult the documentation of the specific
#' functions for details.
#'
#' @return Matrix \code{Xls} containing the modified points (points that did not
#' undergo local search are indicated as NA in this output matrix).
#'
#' @export

variation_localsearch <- function(...){

  # ========== Error catching and default value definitions
  # All error catching and default value definitions are assumed to have been
  # verified in the calling function perform_variation().
  # ==========

  # prepare arguments for calling ls_xyz() function
  varargs <- as.list(sys.call())[-1]

  # Call local search method specified in "type"
  opname <- paste0("ls_", varargs$variation$localsearch$type)
  Xls <- do.call(opname,
                 args = varargs)

  # Truncate if required
  if(trunc.x) Xls <- pmax(0, pmin(1, Xls))

  # Return
  return(Xls)

}
