#' Local search Operators
#'
#' Local search operators for the MOEA/D
#'
#' This routine implements the local search operator for the MOEADr package.
#' This operator is called as any other variation operator, but it presents
#' some specific features that affect the general behavior of .
#'
#' - If the input parameter \code{tau.ls} is present, then this operator is
#' executed once every \doce{tau.ls} iterations.
#' - If the input parameter \code{gamma.ls} is present, then this operator is
#' executed at iterations when the condition \code{runif() < gamma.ls} is
#' verified.
#'
#' The trigger conditions described above (which are not mutually exclusive) are
#' verified independently for every subproblem of the MOEA/D, at each iteration.
#' Whenever the local search is triggered for a given subproblem, it cancels
#' all other variation operators _for that subproblem_ and is executed directly
#' on the incumbent solution.
#'
#' @param X Matrix of candidate solutions (generated in the calling function
#' [perform_variation()])
#' @param Xt Matrix of incumbent solutions
#' @param Yt Matrix of objective function values for the incumbent solutions
#' @param B Matrix of neighborhoods (generated by [define_neighborhood()])
#' @param type type of local search. The list of available local search methods
#' can be generated using \code{get_localsearch_methods()}
#' @param which.x logical vector indicating which subproblems should undergo
#' local search
#' @param trunc.x logical vector indicating whether results should be
#' truncated to the region defined by the box constraints
#' @param ... other parameters (unused, included for compatibility with
#' generic call)
#'
#' @section References:
#' Y. Tan, Y. Jiao, H. Li, X. Wang,
#' "A modification to MOEA/D-DE for multiobjective optimization problems with
#' complicated Pareto sets",
#' Information Sciences 213(1):14-38, 2012.
#'
#' B. Chen, W. Zeng, Y. Lin, D. Zhang,
#' "A new local search-based multiobjective optimization algorithm",
#' IEEE Trans. Evolutionary Computation 19(1):50-73, 2015.
#'
#' @return Matrix \code{X}' containing the modified population
#'
#' @export

variation_localsearch <- function(X, Xt, Yt, B, type, which.x, trunc.x,...){

  # ========== Error catching and default value definitions
  # All error catching and default value definitions are assumed to have been
  # verified in the calling function perform_variation().
  # ==========

  # Isolate subproblems for which local search will be performed
  Bls <- B[which.x, ]
  Xls <- Xt[which.x, ]
  Yls <- Yt[which.x, ]

  # prepare arguments for calling ls_xyz() function
  varargs <- as.list(sys.call())[-1]
  varargs$X <- Xls
  varargs$Y <- Yls
  varargs$B <- Bls

  # Call local search method specified in "type"
  opname <- paste0("ls_", type)
  Xls <- do.call(opname,
                 args = varargs)

}
