#' Local search Operators
#'
#' Local search operators for the MOEA/D
#'
#' This routine implements the local search operator for the MOEADr package.
#' This operator is called as any other variation operator, but it presents
#' some specific features that affect the general behavior of .
#'
#' - If the input parameter \code{tau.ls} is present, then this operator is
#' executed once every \code{tau.ls} iterations.
#' - If the input parameter \code{gamma.ls} is present, then this operator is
#' executed at iterations when the condition \code{runif() < gamma.ls} is
#' verified.
#'
#' The trigger conditions described above (which are not mutually exclusive) are
#' verified independently for every subproblem of the MOEA/D, at each iteration.
#' Whenever the local search is triggered for a given subproblem, it cancels
#' all other variation operators _for that subproblem_ and is executed directly
#' on the incumbent solution.
#'
#' @param Xt Matrix of incumbent solutions
#' @param Yt Matrix of objective function values for the incumbent solutions
#' (generated in [evaluate_population()])
#' @param Vt List containing information regarding the constraint function
#' values for the incumbent solutions (generated in [evaluate_population()])
#' @param bigZ Matrix containing the scalarized function values for the
#' incumbent solutions, generated by the call to [scalarize_values()] within
#' [update_population()]
#' @param bigZ Matrix containing the selection indices for each neighborhood,
#' generated by the call to [order_neighborhood()] within [update_population()]
#' @param B Matrix of neighborhoods (generated by [define_neighborhood()])
#' @param W matrix of weights (created by [generate_weights()]).
#' @param type type of local search. The list of available local search methods
#' can be generated using \code{get_localsearch_methods()}
#' @param which.x logical vector indicating which subproblems should undergo
#' local search
#' @param trunc.x logical vector indicating whether results should be
#' truncated to the region defined by the box constraints
#' @param ... other parameters (unused, included for compatibility with
#' generic call)
#'
#' B. Chen, W. Zeng, Y. Lin, D. Zhang,
#' "A new local search-based multiobjective optimization algorithm",
#' IEEE Trans. Evolutionary Computation 19(1):50-73, 2015.
#'
#' @return Matrix \code{Xls} containing the modified points (points that did not
#' undergo local search are indicated as NA in this output matrix).
#'
#' @export

variation_localsearch <- function(Xt, Yt, Vt, bigZ, sel.indx,
                                  B, W, type, which.x, trunc.x, ...){

  # ========== Error catching and default value definitions
  # All error catching and default value definitions are assumed to have been
  # verified in the calling function perform_variation().
  # ==========

  # prepare arguments for calling ls_xyz() function
  varargs <- as.list(sys.call())[-1]

  # Call local search method specified in "type"
  opname <- paste0("ls_", type)
  Xls <- do.call(opname,
                 args = varargs)

  # Truncate if required
  if(trunc.x) Xls <- pmax(0, pmin(1, Xls))

  # Return
  return(Xls)

}
